[24.01.18] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #15
Opened 2024-01-18 07:45 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이 PR 올립니다.

2024-01-18 11:55 UTC, f-lab-jake requested changes

2024-01-18 11:55 UTC, f-lab-jake commented on 02.programmers-Lv1/025-가운데글자가져오기.ts
> +        : s.slice(startIdx, startIdx + 1);
중복을 줄입시다.

2024-01-18 11:55 UTC, f-lab-jake commented on 03.programmers-Lv2/014-구명보트.ts
> +        }
중복을 줄입시다.

2024-01-18 12:01 UTC, k-jeonghee commented on 03.programmers-Lv2/014-구명보트.ts
> +        }
코드가 더 잘 읽힙니다!

2024-01-18 13:28 UTC, f-lab-jake requested changes

2024-01-18 13:28 UTC, f-lab-jake commented on 02.programmers-Lv1/025-가운데글자가져오기.ts
> +        : s.slice(startIdx, endIdx);
더 잘할수있습니다.

2024-01-19 02:27 UTC, f-lab-jake approved these changes

2024-01-19 02:30 UTC, merged