[24.01.20] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #17
Opened 2024-01-20 09:15 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이 PR 올립니다.

2024-01-20 09:54 UTC, f-lab-jake requested changes

2024-01-20 09:54 UTC, f-lab-jake commented on 02.programmers-Lv1/033-문자열다루기.ts
> +    return false;
`return true` `return false` 뭔가 냄새가 나지 않나요?

그리고 정규식을 써봅시다.

2024-01-20 09:54 UTC, f-lab-jake commented on 02.programmers-Lv1/034-행렬의덧셈.ts
> +    return _.chunk(arr, 2);
통과 못했을거 같은데요?
그리고 의미 자체가 이상합니다.

2024-01-20 09:54 UTC, f-lab-jake commented on 03.programmers-Lv2/020-귤고르기.ts
> +        }
중복을 줄여보세요.

2024-01-20 09:54 UTC, f-lab-jake commented on 03.programmers-Lv2/020-귤고르기.ts
> +        }
요즘 배웠던걸 다시 까먹고있습니다.

2024-01-20 10:40 UTC, k-jeonghee commented on 02.programmers-Lv1/034-행렬의덧셈.ts
> +    return _.chunk(arr, 2);
zip을 억지로 쓰다가 이상한 코드가 되었습니다. lodash를 쓰지 않는 방법이 더 잘 읽히는 것 같아 다시 적용했습니다.

2024-01-20 10:40 UTC, k-jeonghee commented on 03.programmers-Lv2/020-귤고르기.ts
> +        }
중복을 분기 후에 빼는 것만 생각했습니다. 😢

2024-01-20 17:09 UTC, f-lab-jake requested changes

2024-01-20 17:09 UTC, f-lab-jake commented on 03.programmers-Lv2/020-귤고르기.ts
> +        else {
else뺄수잇겟죠?

2024-01-20 17:09 UTC, f-lab-jake commented on 02.programmers-Lv1/034-행렬의덧셈.ts
> +    return arr1.map((rows, rowIdx) =>
zip을 쓰는건 맞아요. 그런데 `flat`의 활용이 문제였습니다.

2024-01-20 17:22 UTC, k-jeonghee commented on 02.programmers-Lv1/034-행렬의덧셈.ts
> +    return arr1.map((rows, rowIdx) =>
너무 어렵게 생각했습니다. 다시 zip을 적용해 구현해보았습니다!

2024-01-21 12:10 UTC, f-lab-jake requested changes

2024-01-21 12:10 UTC, f-lab-jake commented on 02.programmers-Lv1/034-행렬의덧셈.ts
> +    return arr1.map((rows, rowIdx) =>
`rowIdx`를 안쓰려고 `zip`을 쓰는것입니다

2024-01-21 12:10 UTC, f-lab-jake commented on 03.programmers-Lv2/020-귤고르기.ts
> +        k -= count;
커플링이 있어요.

2024-01-21 13:23 UTC, k-jeonghee commented on 03.programmers-Lv2/020-귤고르기.ts
> +        k -= count;
넵, 다시 개선해보았습니다.

2024-01-21 15:18 UTC, f-lab-jake requested changes

2024-01-21 15:18 UTC, f-lab-jake commented on 03.programmers-Lv2/020-귤고르기.ts
> +        else break;
여전히 커플링이 있습니다. `count`를 한번만 써보세요.

2024-01-21 15:23 UTC, k-jeonghee commented on 03.programmers-Lv2/020-귤고르기.ts
> +        else break;
위로 빼내어서 제거했습니다!

2024-01-22 08:20 UTC, f-lab-jake approved these changes

2024-01-22 08:20 UTC, f-lab-jake commented
고친코드에서 제거한 커플링이 뭘까요?

2024-01-22 14:46 UTC, merged