[24.01.21] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #18
Opened 2024-01-21 10:47 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이 PR 올립니다.

2024-01-21 12:06 UTC, f-lab-jake requested changes

2024-01-21 12:06 UTC, f-lab-jake commented on 02.programmers-Lv1/036-최대공약수와최대공배수.ts
> +};
유클리드 호재법으로 풀어보세요

2024-01-21 12:06 UTC, f-lab-jake commented on 03.programmers-Lv2/022-괄호회전하기.ts
> +};
boolean을 리턴하게하고 함수이름을 바꾸세요

2024-01-21 14:08 UTC, k-jeonghee commented on 02.programmers-Lv1/036-최대공약수와최대공배수.ts
> +};
엄청 간결해졌습니다!

2024-01-21 15:19 UTC, f-lab-jake requested changes

2024-01-21 15:19 UTC, f-lab-jake commented on 03.programmers-Lv2/022-괄호회전하기.ts
> +    return stack.length === 0 && true;
좀 이상하죠?

2024-01-21 15:19 UTC, f-lab-jake commented on 03.programmers-Lv2/022-괄호회전하기.ts
> +        answer += +isCorrect;
`number`에다가 `boolean`을 더하면 안됩니다.

2024-01-21 15:29 UTC, k-jeonghee commented on 03.programmers-Lv2/022-괄호회전하기.ts
> +        answer += +isCorrect;
넵, 분기해서 처리하는 것으로 변경했습니다.

2024-01-22 08:24 UTC, f-lab-jake approved these changes

2024-01-22 14:47 UTC, merged