[24.01.24] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #19
Opened 2024-01-24 11:20 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 PR 올립니다.

2024-01-25 04:14 UTC, f-lab-jake requested changes

2024-01-25 04:14 UTC, f-lab-jake commented on 02.programmers-Lv1/039-이상한문자만들기.ts
> +                })
간결하게 써보세요.

2024-01-25 04:14 UTC, f-lab-jake commented on 02.programmers-Lv1/040-크기가작은부분문자열.ts
> +        const str = Number(t.slice(i, p.length + i));
이름이 `str`인데 `number`인게 이상합니다.

2024-01-25 04:14 UTC, f-lab-jake commented on 02.programmers-Lv1/041-삼총사.ts
> +    }
`numbers.entries` + `slice` 활용해 봅시다.

2024-01-25 04:14 UTC, f-lab-jake commented on 03.programmers-Lv2/023-할인행사.ts
> +        if (![...copyMap.values()].reduce((a, b) => a + b)) day++;
`sum` 씁시다.

2024-01-25 04:14 UTC, f-lab-jake commented on 03.programmers-Lv2/023-할인행사.ts
> +    for (let i = 0; i <= discount.length; i++) {
`.entries()`씁시다

2024-01-25 04:14 UTC, f-lab-jake commented on 03.programmers-Lv2/024-n^2배열자르기.ts
> +    return arr;
간결하게 해보세요.

2024-01-25 09:36 UTC, k-jeonghee commented on 03.programmers-Lv2/024-n^2배열자르기.ts
> +    return arr;
함수를 제거하고 바로 적용했습니다.

2024-01-25 09:36 UTC, k-jeonghee commented on 02.programmers-Lv1/041-삼총사.ts
> +    }
멘토님, 여러가지 방법으로 시도해보았는데 `entries()`까지만 적용할 수 있었습니다.
slice를 쓰게 되면 시작값 혹은 종료값을 지정하기가 어렵습니다. 힌트를 조금 주실 수 있을까요?

2024-01-25 16:15 UTC, f-lab-jake commented on 02.programmers-Lv1/039-이상한문자만들기.ts
>                  })
{} 를 없앱시다.

2024-01-25 16:16 UTC, f-lab-jake commented on 02.programmers-Lv1/041-삼총사.ts
> +                const sum = val1 + val2 + val3;
별로 좋은 코드 같지 않죠?
`slice`를 쓰세요.

2024-01-25 16:17 UTC, f-lab-jake commented on 02.programmers-Lv1/040-크기가작은부분문자열.ts
> +        if (num <= Number(p)) count++;
사실 `num`도 별로 안좋습니다. 별 뜻이 없어요. 아예 그렇게 가려면 차라리 `x`같은게 낫습니다. 아니면 이름을 제대로 짓던가요.

2024-01-25 16:17 UTC, f-lab-jake commented on 03.programmers-Lv2/023-할인행사.ts
> +    for (const [i] of discount.entries()) {
`.keys()`가 있어요.

2024-01-25 22:25 UTC, k-jeonghee commented
멘토님, 삼총사 문제는 여러가지 방법으로 시도해보았는데 entries()까지만 적용할 수 있었습니다.
slice를 쓰게 되면 시작값 혹은 종료값을 지정하기가 어렵습니다. 힌트를 조금 주실 수 있을까요?

2024-01-26 07:12 UTC, f-lab-jake commented
시작갑 종료값 지정이 어떤식으로 어렵나요?

2024-01-26 12:43 UTC, k-jeonghee commented
slice를 적용하는 배열이 잘못되었습니다. 다시 개선했습니다!

2024-01-27 03:16 UTC, f-lab-jake approved these changes
매번 꼭 이런 방식으로 짜란 건 아니지만, 이렇게 쉽게 고칠수는 있어야합니다.

2024-01-27 09:23 UTC, merged