[24.01.25] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #20
Opened 2024-01-25 11:31 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이 PR 올립니다.

2024-01-25 16:18 UTC, f-lab-jake requested changes
전체적으로 좀 개선해보세요. 세부적인 개선 방식은 거의 다 알려드렸습니다. 이제 어딜 고칠지부터 스스로 찾아내야합니다.

2024-01-26 03:39 UTC, k-jeonghee commented
불필요한 변수 선언을 제거하고 분기를 줄일 수 있는 코드를 개선해보았습니다.

2024-01-26 11:43 UTC, k-jeonghee commented on 02.programmers-Lv1/042-최소직사각형.ts
> +        heigh.push(w < h ? w : h);
값 비교를 줄일 수 있어 좋은 것 같습니다.

2024-01-26 11:44 UTC, k-jeonghee commented on 02.programmers-Lv1/043-시저암호.ts
> +            return changeChar(char.charCodeAt(0), n);
결과에만 집중했던 것 같아요. 한 번 더 체크하겠습니다.

2024-01-27 03:15 UTC, f-lab-jake approved these changes

2024-01-27 03:15 UTC, f-lab-jake commented on 02.programmers-Lv1/044-가장가까운같은글자.ts
>      return answer;
`map`으로도 할수있습니다

2024-01-27 09:43 UTC, merged