[24.02.03] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #21
Opened 2024-02-03 04:19 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이 PR 올립니다.
- DFS 알고리즘을 공부하면서 백준의 관련 문제들을 풀어보고 있습니다.

2024-02-03 11:10 UTC, f-lab-jake requested changes

2024-02-03 11:10 UTC, f-lab-jake commented on 00.baekjoon/037-2606.ts
> +    visited[x] = true;
아래 for문보다 여기서 `visited[x]` 체크를 하는게 좋습니다. 왜그럴까요?

2024-02-03 11:10 UTC, f-lab-jake commented on 02.programmers-Lv1/046-소수찾기.ts
> +        .map((_, i) => i);
`number` 변수가 가지는 의미가 뭔가요?

2024-02-03 11:46 UTC, k-jeonghee commented on 00.baekjoon/037-2606.ts
> +    visited[x] = true;
dfs 함수가 호출되는 상황은 2가지입니다.
1. 첫 호출: 방문한 노드가 1개도 없음
2. 이후 호출: 노드에 방문한 적이 없음

for문에서 `visited`를 체크할 경우 방문한 노드에 연결된 노드가 없다면 for문이 실행되지 않아 첫 호출 및 연결된 노드가 없는 노드는 방문처리가 되지 않습니다.

2024-02-03 11:46 UTC, k-jeonghee commented on 02.programmers-Lv1/046-소수찾기.ts
> +        .map((_, i) => i);
n까지의 숫자 배열인데 나타내는 의미가 불분명하여 변수명을 수정하고 range를 적용했습니다.

2024-02-03 12:38 UTC, f-lab-jake requested changes

2024-02-03 12:38 UTC, f-lab-jake commented on 02.programmers-Lv1/046-소수찾기.ts
> +    const numRange = _.range(0, n + 1);
이게 약간 낫긴하지만, 리팩토링을 하란게 얘기가 아니었습니다

`numRange`가 무슨 의미를 가지는지 설명을 해보실래요?
일단 의미가 이상하고 저렇게 정의할필요가 없다는걸 깨닫게하기위함임을 알려드립니다.

2024-02-03 12:51 UTC, k-jeonghee commented on 02.programmers-Lv1/046-소수찾기.ts
> +    const numRange = _.range(0, n + 1);
아하 넵, `numRange`는 index를 이용해 만든 n까지의 숫자 배열입니다.
배열을 순회하면서 index가 소수가 아닌 원소에는 0을 할당합니다.

2024-02-03 13:19 UTC, f-lab-jake commented on 02.programmers-Lv1/046-소수찾기.ts
> +    const numRange = _.range(0, n + 1);
넵 그값이 답을 구하는데 왜 필요하죠?

2024-02-03 13:33 UTC, k-jeonghee commented on 02.programmers-Lv1/046-소수찾기.ts
> +    const numRange = _.range(0, n + 1);
다시 보니 index 값이 필요한 것은 아니고 이전에 확인한 적이 있는지 판별(중복 확인 방지)하는 용도로만 필요합니다!

2024-02-06 10:39 UTC, f-lab-jake requested changes

2024-02-06 10:39 UTC, f-lab-jake commented on 02.programmers-Lv1/046-소수찾기.ts
>      }
비효율을 개선해보세요

2024-02-06 14:45 UTC, k-jeonghee commented on 02.programmers-Lv1/046-소수찾기.ts
> +        for (let j = i * i; j <= n; j += i) {
제곱으로 변경해 중복 순회를 쪼금 피해보았습니다.

2024-02-08 08:44 UTC, f-lab-jake commented on 02.programmers-Lv1/046-소수찾기.ts
> +        for (let j = i * i; j <= n; j += i) {
약수가 하나라도 발견되면 소수가 아니란걸 알수있습니다.

2024-02-08 08:45 UTC, f-lab-jake commented on 02.programmers-Lv1/046-소수찾기.ts
> +        for (let j = i * i; j <= n; j += i) {
앗 잘햇습니다.
지금 다시 보니 제 피드백이 잘못되었군요. 불필요한 순회가 아니라 불필요한 if문을 제거해보세요.

2024-02-09 09:34 UTC, k-jeonghee commented on 02.programmers-Lv1/046-소수찾기.ts
> +        for (let j = i * i; j <= n; j += i) {
넵! 합칠 수 있는 부분을 놓쳤습니다😢 불필요한 분기를 제거했습니다.

2024-02-09 12:52 UTC, f-lab-jake requested changes

2024-02-09 12:52 UTC, f-lab-jake commented on 02.programmers-Lv1/046-소수찾기.ts
> +            if (isPrimes[j] && j % i === 0) isPrimes[j] = false;
여기서 불필요한 분기는 `j % i === 0 `입니다. 왜인가요?

2024-02-10 15:17 UTC, f-lab-jake commented on 02.programmers-Lv1/046-소수찾기.ts
> +            if (isPrimes[j] && j % i === 0) isPrimes[j] = false;
제곱이라는게 무슨뜻이죠?

2024-02-10 15:42 UTC, k-jeonghee commented on 02.programmers-Lv1/046-소수찾기.ts
> +            if (isPrimes[j] && j % i === 0) isPrimes[j] = false;
`j`는 `i`의 제곱값으로 시작해 `i`만큼 더해가면서 순회를 하게 되어 `j % i`는 항상 0이 되므로 해당 조건을 제거해도 문제 없습니다.

2024-05-18 03:06 UTC, merged