[24.02.07] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #22
Opened 2024-02-07 12:54 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이 PR 올립니다.

2024-02-08 08:43 UTC, f-lab-jake requested changes

2024-02-08 08:43 UTC, f-lab-jake commented on 03.programmers-Lv2/028-최소피로도.ts
> +    const dfs = (cnt: number) => {
이름을 붙여보세요.

2024-02-08 08:43 UTC, f-lab-jake commented on 03.programmers-Lv2/028-최소피로도.ts
> +                k -= fatigue;
외부 변수 `k`를 변경하지 않는쪽으로 해봅시다.

2024-02-09 09:16 UTC, k-jeonghee commented on 00.baekjoon/038-1012.ts
> +const dfs = (graph: number[][], y: number, x: number) => {
넵, 최소피로도 문제와 함께 recursive로 시작하는 함수명을 붙여보았습니다.

2024-02-09 09:16 UTC, k-jeonghee commented on 02.programmers-Lv1/048-실패율.ts
> +    return [...map].sort((a, b) => b[1] - a[1]).map((v) => v[0]);
코드가 더 길어지긴 했지만 기존 2개의 filter 코드에서 했던 순회를 줄여 속도를 개선했습니다.

2024-02-09 09:16 UTC, k-jeonghee commented on 03.programmers-Lv2/028-최소피로도.ts
> +                k -= fatigue;
줄어든 피로도를 바로 전달해 함수가 호출된 시점의 `remainingFatigue` 값을 활용할 수 있게 되어 재귀호출이 끝나면 다시 더해주는 코드를 제거할 수 있었습니다!
- 개선하면서 counts 배열을 사용하지 않을 수 있는 풀이를 보게 되어 참고하여 적용해보았습니다.

2024-02-09 12:51 UTC, f-lab-jake requested changes

2024-02-09 12:51 UTC, f-lab-jake commented on 00.baekjoon/038-1012.ts
> +const recursiveFindPosition = (graph: number[][], y: number, x: number) => {
`recursive~`는 함수의 내부구현에 대해 알려주는 내용이죠.
쓰는 쪽에선 알필요가 없습니다. 저같으면 `colorMap` 정도로 하겠네요. 실제로 주역할이 `graph` 배열을 변경하는 거잖아요?

2024-02-09 12:51 UTC, f-lab-jake commented on 02.programmers-Lv1/048-실패율.ts
>  }
O(N^2)이죠? O(N) 가능합니다

2024-02-09 12:51 UTC, f-lab-jake commented on 03.programmers-Lv2/028-최소피로도.ts
>                  visited[i] = true;
`visited` 체크와 변경을 함수 앞으로 빼세요

2024-02-09 17:01 UTC, k-jeonghee commented on 00.baekjoon/038-1012.ts
> +const recursiveFindPosition = (graph: number[][], y: number, x: number) => {
넵, 쓰는 쪽에서 알 필요가 없다는 점도 고려하겠습니다! 지렁이가 닿을 수 있는 graph를 그리는 함수라 `colorWormsMap`으로 수정해보았습니다.

2024-02-09 17:01 UTC, k-jeonghee commented on 02.programmers-Lv1/048-실패율.ts
>  }
클리어한 총 인원수를 합하는 것만 생각하느라 반복문을 버리기 어려웠는데 정말 간단한 방법이 있었네요! 요런 패턴도 기억해두겠습니다.

2024-02-09 17:01 UTC, k-jeonghee commented on 03.programmers-Lv2/028-최소피로도.ts
>                  visited[i] = true;
분리 후 코드 흐름이 잘 읽히고, 현재 어느 인덱스에서 재귀 호출 중인지 추적이 쉽게 느껴집니다!
대신 반복문을 통해 어느 인덱스에서도 무조건 함수 호출을 하게 되는데요. 분리하지 않으면 분기에서 방문여부가 걸러지므로 호출 없이 다음으로 넘어갈 수 있습니다. 바로 `return` 할 수 있다면 호출이 큰 영향은 없을까요? 아니면 분리를 해야 좋은 점이 또 있을까요?!

2024-02-10 15:17 UTC, f-lab-jake approved these changes

2024-02-10 15:43 UTC, merged

2024-02-11 06:27 UTC, f-lab-jake commented on 03.programmers-Lv2/028-최소피로도.ts
>                  visited[i] = true;
성능에서 약간 손해는 있을겁니다. 하지만 또 다른 방법으로 보완가능합니다. `visited` 체크와 변경, 그리고 재귀 호출을 묶은 함수를 만들어 사용하면 됩니다.

`visited`를 앞으로 빼게되면 여러군데에서 재귀호출이 있을때에도 정상적으로 동자하게 됩니다.