[24.02.21] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #23
Opened 2024-02-21 08:13 UTC by kjheee

@f-lab-jake
멘토님, 새로운 문제 풀이 PR 올립니다.

2024-02-24 09:51 UTC, f-lab-jake requested changes

2024-02-24 09:51 UTC, f-lab-jake commented on 00.baekjoon/039-1240.ts
> +const links: number[][][] = Array.from(Array(N + 1), () => []);
https://yamoo9.gitbook.io/typescript/types/tuple
튜플타입을 활용해보세요. 어떤점이 나은걸까요?

2024-02-24 09:51 UTC, f-lab-jake commented on 00.baekjoon/039-1240.ts
> +};
답을 찾고도 계속 찾지 않나요?

2024-02-24 11:54 UTC, k-jeonghee commented on 00.baekjoon/039-1240.ts
> +const links: number[][][] = Array.from(Array(N + 1), () => []);
고정된 길이와 순서를 보장 받을 수 있습니다. 
그리고 3차원 배열이다보니 튜플로 했을때 links의 구조가 더 명확하게 보이는 것 같아요.

2024-02-24 11:54 UTC, k-jeonghee commented on 00.baekjoon/039-1240.ts
> +};
조건에 일치한 경우에는 반복문을 벗어날 수 있도록 수정했습니다.

2024-02-26 11:10 UTC, f-lab-jake requested changes

2024-02-26 11:10 UTC, f-lab-jake commented on 00.baekjoon/039-1240.ts
> +        if (count === totalDist) break;
`findPath`가 리턴값을 가지게 하고 그걸 활용하세요

2024-02-27 01:14 UTC, f-lab-jake approved these changes

2024-02-27 01:14 UTC, f-lab-jake commented on 00.baekjoon/039-1240.ts
>  };
잘했습니다

2024-02-27 09:34 UTC, k-jeonghee commented on 00.baekjoon/039-1240.ts
>  };
어떤 반환값을 원하는지와 언제 종료시킬지가 명확하게 보이는 것 같아요. 새롭게 배워갑니다!🎉

2024-02-27 09:34 UTC, merged