[24.03.19] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #26
Opened 2024-03-19 09:30 UTC by k-jeonghee

@f-lab-jake 
멘토님, 알고리즘 문제 풀이 PR 올립니다.

2024-03-20 03:20 UTC, f-lab-jake requested changes

2024-03-20 03:20 UTC, f-lab-jake commented on 00.baekjoon/구현/001-2979.ts
> +const setTimeSlot = (maxTime: number, map: number[][]) => {
`map`타입을 개선하세요.

2024-03-20 03:20 UTC, f-lab-jake commented on 00.baekjoon/완전탐색/002-2309.ts
> +    }
generator 쓰세요

2024-03-20 03:20 UTC, f-lab-jake commented on 00.baekjoon/완전탐색/005-1018.ts
> +const black = ['BWBWBWBW', 'WBWBWBWB', 'BWBWBWBW', 'WBWBWBWB', 'BWBWBWBW', 'WBWBWBWB', 'BWBWBWBW', 'WBWBWBWB'];
지금 풀이도 좋습니다. 그런데 얘들을 쓰지 말고 풀어보세요.

2024-03-23 11:07 UTC, f-lab-jake requested changes

2024-03-23 11:07 UTC, f-lab-jake commented on 00.baekjoon/완전탐색/005-1018.ts
> +                    checkWhite++;
`checkBlack`아닌가요?

2024-03-23 14:40 UTC, k-jeonghee commented on 00.baekjoon/완전탐색/005-1018.ts
> +                    checkWhite++;
해당 if문은 짝수가 '`W`' 홀수가'`B`'인 `white` 체스판을 기준으로 카운트합니다.
순회 후 `checkWhite`의 값이 더 적으면 `black` 체스판을 만들기 위한 최솟값,
`checkBlack`의 값이 더 적으면 `white` 체스판을 만들기 위한 최솟값이 됩니다. 
둘 중 어떤 경우가 되어도 최솟값을 찾습니다.

2024-03-24 12:43 UTC, f-lab-jake commented on 00.baekjoon/완전탐색/005-1018.ts
> +                    checkWhite++;
흠 그러면 이름을 바꿔야 하지 않나요? 그리고 if문의 구조도 개선할수 있겠습니다

2024-03-25 01:03 UTC, f-lab-jake requested changes

2024-03-25 01:03 UTC, f-lab-jake commented on 00.baekjoon/완전탐색/005-1018.ts
> +            count[color] += 1;
클레버한 트릭입니다.

2024-03-25 01:03 UTC, f-lab-jake commented on 00.baekjoon/완전탐색/005-1018.ts
> +            count[color] += 1;
let을 없애고,
`expectedColor`란 변수를 도입해서 더 리팩토링 해보세요

2024-03-25 01:59 UTC, k-jeonghee commented on 00.baekjoon/완전탐색/005-1018.ts
> +            count[color] += 1;
`expectedColor`를 매개변수로 전달해서 의미에 맞게 함수명을 수정해보았습니다.

2024-03-26 04:45 UTC, f-lab-jake requested changes

2024-03-26 04:45 UTC, f-lab-jake commented on 00.baekjoon/완전탐색/005-1018.ts
>              if ((i + j) % 2 === 0) {
```ts
const expectedColor = (i + j) % 2 === 0 ? "B" : "W"
```
이렇게 해볼까요?

2024-03-28 11:55 UTC, f-lab-jake approved these changes

2024-03-28 11:55 UTC, f-lab-jake approved these changes

2024-03-28 11:58 UTC, merged