[24.03.30] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #27
Opened 2024-03-30 12:15 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이 PR 올립니다.

2024-04-01 02:19 UTC, f-lab-jake requested changes

2024-04-01 02:19 UTC, f-lab-jake commented on 03.programmers-Lv2/031-모음사전.ts
> +    dictionary.sort();
`sort`를 안써도 되도록 해보세요

2024-04-01 04:46 UTC, k-jeonghee commented on 03.programmers-Lv2/031-모음사전.ts
> +    dictionary.sort();
전체 배열을 만들고 싶지 않아서 제너레이터를 요리조리 수정해봤는데 정렬이 쉽지 않았습니다. 
기존에 생각했던 풀이로 다시 수정하였습니다.

2024-04-01 14:42 UTC, f-lab-jake requested changes

2024-04-01 14:42 UTC, f-lab-jake commented on 03.programmers-Lv2/031-모음사전.ts
> +    return answerMap.get(word);
Generator를 쓰지 말란 얘기는 아니었습니다!
쓰되, 기존의 비효율적인 부분을 개선하세요

2024-04-02 01:46 UTC, k-jeonghee commented
이전 풀이의 `dfs` 부분을 `generator`로 대체하는 방법으로 개선했습니다.
타입 지정과 위임 시 실행 흐름이 조금 어렵습니다 🥲

2024-04-02 01:56 UTC, f-lab-jake requested changes

2024-04-02 01:56 UTC, f-lab-jake commented on 03.programmers-Lv2/031-모음사전.ts
> +    yield* combination();
`count`라는 외부변수와 결합하는걸 피하세요. 그리고 `combination` 저번에 알려준 방식을 참고하세요

2024-04-02 10:28 UTC, f-lab-jake requested changes

2024-04-02 10:28 UTC, f-lab-jake commented on 03.programmers-Lv2/031-모음사전.ts
> +function* generateWords<T>(xs: T[], str: string = ''): Iterable<string> {
`str`이란 인자를 쓰지마세요. 대신 `n: number`이라는 인자를 쓰세요.
그리고 `generateWords`란 함수의 '의미'에 대해서 생각해보세요

2024-05-18 03:06 UTC, merged