[24.04.06] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #28
Opened 2024-04-06 08:54 UTC by k-jeonghee

@f-lab-jake 
멘토님, 알고리즘 문제 풀이 PR 올립니다.

2024-04-07 09:18 UTC, f-lab-jake requested changes

2024-04-07 09:18 UTC, f-lab-jake commented on LeetCode/207-CourseSchedule.ts
> +    }
중복을 제거하세요

2024-04-07 09:18 UTC, f-lab-jake commented on 04.programmers-Lv3/002-네트워크.ts
> +        if (visited[comIdx]) return 0;
리턴값을 쓰려는 의도는 아주 좋습니다.
그런데 사실 이경우엔 `isNetworkConnected`를 정의했다기엔 좀 애매합니다.

2024-04-07 09:18 UTC, f-lab-jake commented on 04.programmers-Lv3/002-네트워크.ts
> +            if (computers[comIdx][linkIdx]) isNetworkConnected(linkIdx);
실제로 `isNetworkConnected`의 리턴값을 활용하지 않고있죠? 활용해도 큰 의미는 없습니다.

암튼 이 경우는 `isNetworkConnected`가 변경을 발생시키지 않도록 분리하는게 불가능하니 이정도가 최선입니다.

2024-04-07 15:42 UTC, k-jeonghee commented on 04.programmers-Lv3/002-네트워크.ts
> +            if (computers[comIdx][linkIdx]) isNetworkConnected(linkIdx);
반환값을 사용하지 않는 부분이 걸려서 다른 풀이로 한번 개선해보았습니다.

2024-04-07 15:42 UTC, k-jeonghee commented on LeetCode/207-CourseSchedule.ts
> +    }
선행 강의 필요 여부를 확인하는 함수를 활용해보았습니다.

2024-04-08 02:14 UTC, f-lab-jake requested changes

2024-04-08 02:14 UTC, f-lab-jake commented on LeetCode/207-CourseSchedule.ts
> +    }
`tryCourse`정도가 좋겠네요.
`can*`이면 boolean을 리턴하길 기대하게됩니다.

2024-04-08 02:20 UTC, k-jeonghee commented on LeetCode/207-CourseSchedule.ts
> +    }
넵! 🫡

2024-04-08 15:53 UTC, f-lab-jake approved these changes

2024-04-08 16:04 UTC, merged