[23.12.16] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #3
Opened 2023-12-16 14:18 UTC by dlfeksgo

@f-lab-jake 
멘토님, 알고리즘 5문제 풀이 PR 올립니다.

- 조이스틱 문제는 이해가 잘 되지 않습니다. 특히 `minMove` 를 구하는 부분이 와닿지 않습니다.
우선 함께 올리고 계속 고민해보도록 하겠습니다.

2023-12-18 05:32 UTC, f-lab-jake requested changes
이진탐색 문제  세트를 푸신거 같은데요.
어떤 문제에 이진탐색을 적용할수 있는지 그 조건을 생각해봅시다

2023-12-18 05:32 UTC, f-lab-jake commented on 00.baekjoon/029-2512.ts
> +console.log(result);
시간복잡도가 얼마인가요? 왜 이진탐색을 써야겠다고 생각햇나요? 다른방법은 없을까요?

2023-12-18 07:25 UTC, dlfeksgo commented on 00.baekjoon/029-2512.ts
> +console.log(result);
`O(N logN)`입니다. 
이진탐색 적용 조건은 제한된 값 내 모든 케이스에서 최선의 값이 되는 최솟값 혹은 최댓값을 구하는 경우로 생각했습니다.
이 문제는 탐색 범위가 좁혀지지 않으면 O(n2)이 되어 이진탐색을 적용했는데 다른 접근을 위한 힌트가 있을까요?

2023-12-18 08:37 UTC, f-lab-jake commented on 00.baekjoon/029-2512.ts
> +console.log(result);
아 제가 문제를 잘못읽었네요. 이진탐색이 의도된 풀이가 맞습니다.
> 이진탐색 적용 조건은 제한된 값 내 모든 케이스에서 최선의 값이 되는 최솟값 혹은 최댓값을 구하는 경우로 생각했습니다.

요건 이진탐색을 쓸수있는 필요조건이지 충분조건은 아닙니다. 충분조건이 뭘까요?

2023-12-18 11:01 UTC, dlfeksgo commented on 00.baekjoon/029-2512.ts
> +console.log(result);
케이스들을 정렬할 수 있고, 작게 나눌 수 있는 경우입니다.

2023-12-18 11:56 UTC, f-lab-jake commented on 00.baekjoon/029-2512.ts
> +console.log(result);
> 케이스들을 정렬할 수 있고, 작게 나눌 수 있는 경우입니다.

요것도 모호한 기준입니다. 자세한 내용은 수요일 멘토링때 얘기나누죠. 그전까지 좀더 생각해서 정리해주세요.

2023-12-18 12:49 UTC, dlfeksgo commented on 00.baekjoon/029-2512.ts
> +console.log(result);
넵!

2023-12-25 04:20 UTC, f-lab-jake requested changes

2023-12-25 04:20 UTC, f-lab-jake commented on 03.programmers-Lv2/001-조이스틱.ts
> +    let minCursorCount = chars.length - 1;
우선 `changeCount`를 도입한것 아주 잘했습니다.

2023-12-25 04:20 UTC, f-lab-jake commented on 03.programmers-Lv2/001-조이스틱.ts
> +        chageCount += char;
`changCounte`를 구하는 로직도 분리합시다.

2023-12-25 04:20 UTC, f-lab-jake commented on 03.programmers-Lv2/001-조이스틱.ts
> +        let cursorCount = i + 1;
요게 의미가 뭔가요. `i`에 대해서 순회하는게 왜 그렇게 하고 있는거죠?

2023-12-25 04:20 UTC, f-lab-jake commented on 03.programmers-Lv2/001-조이스틱.ts
>          );
주석을 다는 것도 좋은 방법입니다. 그런데 코드 자체를 더 개선할수 있는 상황으로 보입니다.

2023-12-25 09:38 UTC, k-jeonghee commented on 03.programmers-Lv2/001-조이스틱.ts
> +        let cursorCount = i + 1;
현재 확인하고 있는 문자열이 몇 번째에 있는지 파악하기 위해서 사용했습니다.

2023-12-25 09:39 UTC, k-jeonghee commented on 03.programmers-Lv2/001-조이스틱.ts
>          );
반복되는 코드를 변수로 빼보았습니다.

2023-12-25 10:13 UTC, f-lab-jake requested changes

2023-12-25 10:13 UTC, f-lab-jake commented on 03.programmers-Lv2/001-조이스틱.ts
>          );
이 코드를 말로 설명해봅시다.

2023-12-25 10:13 UTC, f-lab-jake commented on 03.programmers-Lv2/001-조이스틱.ts
>      const chars = name.split('').map(findChar);
`chars`란 이름이 안좋네요. `distances`정도면 어떨까요?

2023-12-25 11:28 UTC, k-jeonghee commented on 03.programmers-Lv2/001-조이스틱.ts
>          );
1. `name`의 각 문자별 최소 `changeCount`의 배열인 chars(변경 후 distances)를 순회합니다.
2. 각 순회는 현재 확인 중인 문자로 해당 문자까지 이동 시 `cursorCount`가 1회 추가됩니다. 이를 위해 배열의 index를 활용합니다.
3. while문은 다음 문자가 'A'인지 확인하고, 맞다면 `cursorCount`를 올려 그 다음도 'A'인지 확인합니다.
while문을 통과한 뒤의 `cursorCount`는 현재 문자까지 이동에 필요한 커서 수와 그 다음 'A'의 수를 포함합니다.
4. 전체 문자 길이에서 while문을 통과한 뒤의 `cursorCount`를 빼면 'A'를 지나치고 남은 문자의 길이(변경 후 rest)가 됩니다.
5. `minCursorCount`는 순회하는 문자를 만들어내는 모든 경우의 수 중 가장 작은 값입니다.
최솟값이 `전체 문자 길이 - 1`가 아닐 수도 있는 경우는 A가 연속으로 붙어 있어 커서 이동이 필요하지 않은 경우이므로 이를 고려해 비교 조건을 추가합니다.
a. 정방향으로만 이동
b. 정방향으로 이동하다가 역방향으로 전환합니다. (이동거리 * 2) + A를 제외하고 남은 문자
c. 처음부터 역방향으로 이동하다가 다시 정방향으로 전환합니다. (A를 제외하고 남은 문자 * 2) + 정방향 이동 거리

2023-12-25 11:28 UTC, k-jeonghee commented on 03.programmers-Lv2/001-조이스틱.ts
>      const chars = name.split('').map(findChar);
distances로 바꾸면서 map의 콜백함수명도 변경해보았어요.

2024-01-10 12:20 UTC, k-jeonghee commented
@f-lab-jake 
멘토님, 순회하는 각 문자의 위치에서 주어진 단어를 완성할 수 있는 값들 중에 최솟값을 찾아야 했어요.
그래서 말씀해주신 3가지(정방향/역방향/돌아가기)값을 각각 구하는 것이 반복문 순회마다 이루어져야해서 기존 코드를 조금 더 이해하기 쉽도록 함수로 분리해보았습니다.

2024-01-11 07:51 UTC, f-lab-jake requested changes

2024-01-11 07:51 UTC, f-lab-jake commented on 00.baekjoon/031-1654.ts
> +}
이런것도 만들어놓은 binary search 함수 복붙해서 쓰세요.

2024-01-11 07:51 UTC, f-lab-jake commented on 03.programmers-Lv2/001-조이스틱.ts
> +    }
여기서 `charIdx`로 순회하는게 잘 이해가 안됩니다.

2024-01-11 08:50 UTC, k-jeonghee commented on 00.baekjoon/031-1654.ts
> +}
이후 브랜치에서 binary search를 구현하여 적용해두었습니다!

2024-01-11 08:52 UTC, k-jeonghee commented on 03.programmers-Lv2/001-조이스틱.ts
> +    }
주어진 문자를 무조건 첫 번째 문자의 위치에서 만들 수 있는 최솟값이라고 생각해 풀기가 어려웠습니다. 
각 문자의 위치마다 문자를 완성할 수 있는 값을 구해야 하며, 문자 뒤에 오는 A의 갯수에 따라 최솟값이 달라집니다.
그래서 `charIdx`는 `1. 현재 확인 중인 문자의 위치` `2. 문자 다음에 오는 'A'의 갯수 확인`을 위해 필요합니다. 
- 문자의 기본값은 'A'이므로 연속된 'A'가 많을수록 조작수가 줄어듭니다.
<br/>

[예시] `name`이 `'AAB'`라면 3번 계산합니다.
1. `charIdx 0 - 'A'` 에서 'AAB'를 만드는데 필요한 조작수
2. `charIdx 1 - 'A'` 에서 'AAB'를 만드는데 필요한 조작수 
3. `charIdx 2 - 'B'` 에서 'AAB'를 만드는데 필요한 조작수
- 각 순회마다 최솟값을 찾아 할당합니다.(`minMoveCount`)
- 할당된 `minMoveCount`는 다음 순회의 결과들과 비교하는데 사용되며 더 작은 값을 찾습니다.(`getMinMoveFromChar`)

2024-04-17 23:24 UTC, merged