[23.12.21] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #4
Opened 2023-12-21 14:14 UTC by dlfeksgo

@f-lab-jake 
멘토님 새로운 문제 풀이 PR 올립니다!

2023-12-22 02:04 UTC, f-lab-jake requested changes

2023-12-22 02:04 UTC, f-lab-jake commented on 01.programmers-Lv0/037.ts
> +        answer = q * r;
그냥 return을 하는게 낫습니다. 왜일까요?

2023-12-22 02:04 UTC, f-lab-jake commented on 01.programmers-Lv0/039.ts
> +    if (number.length > 19) {
없어도되는 분기입니다. 심지어 위험하기도 합니다. 왜일까요?

2023-12-22 02:04 UTC, f-lab-jake commented on 03.programmers-Lv2/001-조이스틱.ts
> +    }
이해가 되는 코드로 고쳐봅시다. 슬랙에서 힌트는 드렸습니다.

2023-12-22 02:04 UTC, f-lab-jake commented on templates/bs.ts
> +};
여기서 `start` `end`인자가 별로입니다.

2023-12-22 09:32 UTC, dlfeksgo commented on 00.baekjoon/033-10816.ts
> +let answer = '';
`answer`라는 결과물을 한 번에 만들려고 하는 시도입니다. 결과를 예측하기 어려워 출력 전까지의 중간 과정이 불안하게 느껴집니다.
그런데 number 타입처럼 0으로 초기화 한 뒤에 값을 완성해나가는 것도 피하는 것이 좋을까요?

2023-12-22 09:33 UTC, dlfeksgo commented on 01.programmers-Lv0/037.ts
> +        answer = q * r;
if문 뒤에 다른 작업이 없고, 분기에 따라 결과를 반환하면서 함수가 종료되므로 분기별로 return 해주면 그 다음 코드를 확인할 필요 없이 함수를 종료할 수 있습니다.

2023-12-22 09:33 UTC, dlfeksgo commented on 01.programmers-Lv0/039.ts
> +    if (number.length > 19) {
문제에 없는 조건이면서 `19`라는 값의 정의도 주관적이라 분기로 인해 원하는 결과를 얻지 못할 수 있습니다.

2023-12-23 09:42 UTC, k-jeonghee commented on 03.programmers-Lv2/001-조이스틱.ts
> +    }
코드에 큰 변화는 없지만 변수들의 역할을 이해하기 쉬운 이름으로 정정했습니다.

2023-12-25 04:26 UTC, f-lab-jake requested changes

2023-12-25 04:26 UTC, f-lab-jake commented on 00.baekjoon/029-2512.ts
> +};
이 `bs`는 외부 변수인 `mid`를 수정합니다. 그렇게 하지 말아봅시다. return값을 갖게하고 그걸 활용합시다.

2023-12-25 04:26 UTC, f-lab-jake commented on 00.baekjoon/029-2512.ts
>      if (sum <= totalBudget) {
이 `bs`는 순수 bineary search만 하는 것이 아닌, 이 2512번 문제의 특수한 조건, `totalBudget`과 관련된 로직을 포함하고 있습니다. 이걸 빼봅시다. 이후의 다른 문제에 대해서도 마찬가지 입니다.

2023-12-25 04:26 UTC, f-lab-jake commented on 00.baekjoon/035-10162.ts
> +    });
`map`에선 부수효과를 발생시키지 않는것이 관례입니다. 여기서 부수효과는 어느부분일까요?

2023-12-25 04:26 UTC, f-lab-jake commented on 00.baekjoon/033-10816.ts
> +const answer = M.map((v) => countByRange(N, v, v));
`countByRange`는 내부적으로 이진탐색을 쓰는군요.
배열 + 이진탐색말고 더 적합한 자료구조를 선택하는 길도 있습니다.

2023-12-25 17:32 UTC, k-jeonghee commented on 00.baekjoon/035-10162.ts
> +    });
n의 값을 변경하는 부분입니다. for...of문으로 대체하여 원하는 값만 배열에 담는 것으로 수정해보았습니다.

2023-12-25 17:35 UTC, k-jeonghee commented on 00.baekjoon/033-10816.ts
> +const answer = M.map((v) => countByRange(N, v, v));
값의 조회를 빠르게 해야하므로 해시를 이용하는 것이 좋을 것 같아 Map을 사용해보았습니다.

2023-12-25 17:42 UTC, k-jeonghee commented on 00.baekjoon/029-2512.ts
>      if (sum <= totalBudget) {
관련 문제 3개의 bs 함수를 수정해보았는데 문제마다 특수한 조건 관련 로직을 더 분리할 방법이 떠오르지 않습니다..

2023-12-26 02:21 UTC, f-lab-jake requested changes

2023-12-26 02:21 UTC, f-lab-jake commented on 00.baekjoon/029-2512.ts
> +        bs(totalBudget, mid + 1, high);
`target`이 맞겠죠?

2023-12-26 02:21 UTC, f-lab-jake commented on 00.baekjoon/029-2512.ts
> +    let sum = calcSum(mid);
여전히 분리가 안되어있습니다.
참고해보라고한 라이브러리의 설계를 따라해봅시다.

2023-12-26 04:39 UTC, k-jeonghee commented
@f-lab-jake 
멘토님, binary search 함수를 `[template/bs.ts]` 파일에 분리하고 관련 문제들에 적용했습니다.

2023-12-26 05:27 UTC, f-lab-jake approved these changes

2023-12-26 05:27 UTC, f-lab-jake commented on 00.baekjoon/029-2512.ts
> +const maxBudget = binarySearch(budgets, totalBudget, low, high, comparator);
잘했습니다. `comparator`를 인자로 받는 고차함수로 만드는게 정답입니다. 비로소`binarySearch` 함수가 `comparator`를 바꿔끼우는것으로 재사용 가능해졌습니다.

2023-12-26 06:44 UTC, merged