[23.12.25] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #5
Opened 2023-12-25 09:09 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이 PR 올립니다.

2023-12-25 10:11 UTC, f-lab-jake requested changes

2023-12-25 10:11 UTC, f-lab-jake commented on 01.programmers-Lv0/050-qrCode.ts
> +        })
의도하는게 `map`이 맞을까요?

그리고 한가지 안좋은 동작에 의존하고있습니다.

2023-12-25 10:11 UTC, f-lab-jake commented on 02.programmers-Lv1/003-완주하지못한선수.ts
> +        else map.set(person, map.get(person) + 1);
`1`과 `+ 1`의 `1`은 서로 커플링되어 있습니다. 왜일까요?
그 커플링을 제거해봅시다.

2023-12-25 10:11 UTC, f-lab-jake commented on 03.programmers-Lv2/004-의상.ts
> +        } else closet[category] = [name];
`closet[category] = [...closet[category] ?? [], name];`
이런 방법이 있습니다. 그리고 이럴땐 그냥 `closet[category]`를 변경하는게 낫습니다.

2023-12-25 17:11 UTC, k-jeonghee commented on 01.programmers-Lv0/050-qrCode.ts
> +        })
배열로 반환하면 좋을 것 같아 map을 먼저 떠올던 것인데 if문에 해당하지 않는 값은 undefined를 반환하게 됩니다.
결과는 나오지만 의도한대로 동작한 것은 아닙니다..! 필터된 값만 반환할 수 있도록 코드를 수정하였습니다.

2023-12-25 17:17 UTC, k-jeonghee commented on 02.programmers-Lv1/003-완주하지못한선수.ts
> +        else map.set(person, map.get(person) + 1);
분기에 따라 객체의 값 조회와 수정을 각각 시도하고 있습니다. 이렇게 되면 수정이 일어나도 다른 코드에서는 제대로 된 값을 조회하지 못하는 등의 위험이 있습니다. 조회/수정 함수를 분리해서 처리하는 방법을 시도해보았는데 이 방법도 커플링 제거라고 할 수 있을까요?

2023-12-25 17:21 UTC, k-jeonghee commented on 03.programmers-Lv2/004-의상.ts
> +        } else closet[category] = [name];
closet 객체의 값을 배열에서 number 타입으로 변경하여 적용해보았습니다.

2023-12-26 02:18 UTC, f-lab-jake commented on 02.programmers-Lv1/003-완주하지못한선수.ts
> +        else map.set(person, map.get(person) + 1);
저기 `1`은 사실 `0 + 1`입니다.

2023-12-26 02:20 UTC, f-lab-jake requested changes

2023-12-26 02:20 UTC, f-lab-jake commented on 02.programmers-Lv1/003-완주하지못한선수.ts
>      }
어차피 분리가 안되는 동작인 `getParticipant`와 `setParticipant`로 나누는건 의미가 없습니다.

2023-12-26 02:20 UTC, f-lab-jake commented on 02.programmers-Lv1/003-완주하지못한선수.ts
>      }
`map.get(p) ?? 0`를 활용해봅시다.

2023-12-26 02:44 UTC, k-jeonghee commented on 02.programmers-Lv1/003-완주하지못한선수.ts
>      }
넵 다시 확인해보겠습니다!

2023-12-26 05:25 UTC, f-lab-jake requested changes

2023-12-26 05:25 UTC, f-lab-jake commented on 02.programmers-Lv1/003-완주하지못한선수.ts
> +        else map.set(person, map.get(person) ?? +1);
`has`와 `get`을 따로 부르지 말아보세요. 그리고 그게 왜 안좋은지도 생각해봅시다.

2023-12-26 16:10 UTC, f-lab-jake requested changes

2023-12-26 16:10 UTC, f-lab-jake commented on 02.programmers-Lv1/003-완주하지못한선수.ts
> +        else map.set(person, (map.get(person) ?? 0) + 1);
설명이 좀 부족했나보네요. `has` 자체를 절대 쓰지말란얘기가 아니라, `has`해놓고 `get`을 하는게 낭비라는 이야기입니다. 마찬가지로 `get`을 두번쓰는것도 낭비입니다.

2023-12-28 10:11 UTC, f-lab-jake approved these changes

2023-12-28 10:14 UTC, merged