[23.12.29] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #6
Opened 2023-12-29 10:47 UTC by k-jeonghee

@f-lab-jake 
멘토님 새로운 문제 풀이 PR 드립니다!

2023-12-29 12:14 UTC, f-lab-jake requested changes

2023-12-29 12:14 UTC, f-lab-jake commented on 01.programmers-Lv0/051-문자개수세기.ts
> +        const data = (map.get(char) ?? 0) + 1;
요거 둘다 할필욘 없죠?

2023-12-29 12:14 UTC, f-lab-jake commented on 01.programmers-Lv0/051-문자개수세기.ts
> +    );
요런거 그냥
```ts
const lower = "abcdefghijklmnopqrstuvwxyz";
const upper = lower.toUpper()
```
이런식으로 해도 괜찮습니다. 이쪽은 적어도 코드를 해석을 하진 않아도 되죠.

2023-12-29 12:14 UTC, f-lab-jake commented on 01.programmers-Lv0/052-배열만들기.ts
> +    }
lodash의 `range`함수에 대해 배워서 적용해봅시다.

2023-12-29 12:14 UTC, f-lab-jake commented on 02.programmers-Lv1/003-달리기경주.ts
> +        map.set(callName, map.get(callName) - 1);
`map.get(callName) - 1` 요 값이 결국 뭐죠?

2023-12-29 12:14 UTC, f-lab-jake commented on 02.programmers-Lv1/004-추억점수.ts
> +    }
`push`를 쓰지말아봅시다. 여전히 코드에 끌려다니고 있습니다.

2023-12-29 12:14 UTC, f-lab-jake commented on 04.programmers-Lv3/001-베스트앨범.ts
> +        });
빼봅시다 이것도.

2023-12-29 12:14 UTC, f-lab-jake commented on 04.programmers-Lv3/001-베스트앨범.ts
> +    const map = new Map();
더나은 변수명을 생각해봅시다.

2023-12-30 04:24 UTC, k-jeonghee commented
@f-lab-jake 
멘토님 리뷰 참고하여 코드 개선해보았습니다.

2023-12-30 05:10 UTC, f-lab-jake requested changes

2023-12-30 05:10 UTC, f-lab-jake commented on 01.programmers-Lv0/051-문자개수세기.ts
> +    });
줄여봅시다

2023-12-30 05:10 UTC, f-lab-jake commented on 02.programmers-Lv1/003-달리기경주.ts
> +        map.set(callName, rank - 1);
잘했습니다. 이렇게 같은 의미를 가진 값을 여러가지 방법으로 표현하는걸 피합시다.

그리고 `players`에 대한 변경 동작과 `map`에 대한 변경동작에 커플링이 있습니다. 함수를 도입해 제거해봅시다.

2023-12-30 05:10 UTC, f-lab-jake commented on 04.programmers-Lv3/001-베스트앨범.ts
>          }
`flatMap`을 공부해서 적용해봅시다.

2023-12-30 08:35 UTC, f-lab-jake requested changes

2023-12-30 08:35 UTC, f-lab-jake commented on 02.programmers-Lv1/003-달리기경주.ts
> +        map.set(callName, rank - 1);
`replaceRaking`의 동작을 제가 잘못 짐작했네요.
`players`따로 `map`따로 수정을 하지 말란 얘기였습니다.

2023-12-30 08:35 UTC, f-lab-jake commented on 04.programmers-Lv3/001-베스트앨범.ts
>  }
더 잘짤수있습니다.

2024-01-02 14:35 UTC, k-jeonghee commented on 04.programmers-Lv3/001-베스트앨범.ts
>  }
재생수 상위 2개를 찾으면 그 다음 루프는 돌지 않도록 수정해보았습니다.

2024-01-11 05:14 UTC, f-lab-jake approved these changes

2024-01-11 07:16 UTC, merged