[24.01.05] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #7
Opened 2024-01-05 08:00 UTC by k-jeonghee

@f-lab-jake 
멘토님 새로운 문제 풀이 PR 드립니다.
이전 PR 2개에도 수정사항이 있는데 함께 봐주시면 감사드리겠습니다. 🙇🏻‍♀️

2024-01-06 15:33 UTC, f-lab-jake requested changes

2024-01-06 15:33 UTC, f-lab-jake commented on 01.programmers-Lv0/055-가까운1찾기.ts
> +        if (i > idx && v === 1) return i;
한번 `i > idx`를 만족하면 그 뒤론 계속 만족합니다.
그런데도 매번 확인하겠죠. 주어진 성질을 이용하지 않으면 풀이가 덜 효율적이게 됩니다.

2024-01-06 15:33 UTC, f-lab-jake commented on 02.programmers-Lv1/003-달리기경주.ts
> +    }
`replacePlayer(from: number, to: number)` 란 함수를 만들어봅시다.

2024-01-06 15:33 UTC, f-lab-jake commented on 02.programmers-Lv1/004-추억점수.ts
> +        return sum;
lodash에 `sum`이 있습니다.

2024-01-06 15:33 UTC, f-lab-jake commented on 02.programmers-Lv1/005-공원산책.ts
> +    let [x, y]: number[] = [];
그냥 `let x, y;`합시다. 의미없이 읽는사람한테 해석을 시키는걸 피합시다.

2024-01-06 15:33 UTC, f-lab-jake commented on 02.programmers-Lv1/005-공원산책.ts
> +    const canMove = (x: number, y: number) => {
`canMove`가 아니라 `isValidPosition`이 맞겠죠?
함수 자체의 의미가 아니라 쓰임에 따라 명명해버렸습니다.

2024-01-06 15:33 UTC, f-lab-jake commented on 02.programmers-Lv1/005-공원산책.ts
> +        let flag = true;
`flag` 같은 변수명은 읽는 사람으로하여금 진짜 이름이 뭔지 해석하게 시킵니다. 그냥 봉인합시다.
사실 `canMove`가 `flag`의 진짜 이름입니다.

2024-01-06 15:33 UTC, f-lab-jake commented on 02.programmers-Lv1/006-같은숫자는싫어.ts
> +        if (v === arr[i - 1]) answer.pop();
넣었다 빼지 말아볼까요?

2024-01-06 15:33 UTC, f-lab-jake commented on 03.programmers-Lv2/004-올바른괄호.ts
> +        if (bracket === ')' && stack[stack.length - 1] === '(') stack.pop();
`stack.at(-1)`을 쓸수있습니다.

2024-01-06 15:33 UTC, f-lab-jake commented on 03.programmers-Lv2/005-프로세스.ts
> +        const value = queue.shift() as number[];
as 필요없지 않나요?

2024-01-06 15:33 UTC, f-lab-jake commented on 03.programmers-Lv2/005-프로세스.ts
> +    const queue = priorities.map((v, i) => [v, i]);
`entries`를 하고 `i`, `v` 순서를 뒤에서 반대로 쓰면됩니다.

2024-01-06 15:33 UTC, f-lab-jake commented on 04.programmers-Lv3/001-베스트앨범.ts
> +        return musicIds.splice(0, 2);
정 `push`를 쓴다면, 2개까지만 구하고 return하거나 할때 더 효율적이니 의미를 찾을수 있습니다. 그게 아니면 `filter`가 낫겠죠.

2024-01-06 15:33 UTC, f-lab-jake commented on 03.programmers-Lv2/003-기능개발.ts
> +}
잘 이해가 안됩니다. 왜 맞는 답인지 설명해볼까요? 아니면 이해하기 쉽게 고치는 방법도 있습니다.

2024-01-06 17:53 UTC, k-jeonghee commented on 04.programmers-Lv3/001-베스트앨범.ts
> +        return musicIds.splice(0, 2);
마지막에 수정한 커밋이 현재 PR에서는 나타나지 않습니다.
https://github.com/k-jeonghee/algorithm/blob/a87c82e8f8880257ec38cbb98e9c1a2c42fcecbb/04.programmers-Lv3/001-%EB%B2%A0%EC%8A%A4%ED%8A%B8%EC%95%A8%EB%B2%94.ts
이 코드로 한번 봐주세요!

2024-01-06 19:34 UTC, k-jeonghee commented on 01.programmers-Lv0/055-가까운1찾기.ts
> +        if (i > idx && v === 1) return i;
`I > idx` 를 만족하는 값으로 순회해 조건문을 줄였습니다.

2024-01-06 19:35 UTC, k-jeonghee commented on 02.programmers-Lv1/003-달리기경주.ts
> +    }
변경하면서 Map 대신 객체를 사용해 괄호표기법으로 구조를 맞춰보았습니다. `replacePlayer`를 두번 호출하는 방법도 고민해봤는데 분기가 깔끔하게 되지 않아서 한번만 하는 것으로 적용했습니다.

2024-01-06 19:41 UTC, k-jeonghee commented on 02.programmers-Lv1/004-추억점수.ts
> +        return sum;
lodash의 sum을 사용하기 위해 기존보다 map을 한 번 더 쓰게 됩니다. 잘못된 접근일까요?

2024-01-06 19:41 UTC, k-jeonghee commented on 02.programmers-Lv1/005-공원산책.ts
> +    let [x, y]: number[] = [];
x,y를 할당 전에 사용했다는 에러가 나서 0으로 초기화 해주었습니다.

2024-01-06 19:41 UTC, k-jeonghee commented on 02.programmers-Lv1/006-같은숫자는싫어.ts
> +        if (v === arr[i - 1]) answer.pop();
조건에 부합하는 값만 push 하도록 변경했습니다.

2024-01-06 19:42 UTC, k-jeonghee commented on 03.programmers-Lv2/005-프로세스.ts
> +        const value = queue.shift() as number[];
없으면 에러가 나서 as 대신 단언 연산자로 대체했습니다.

2024-01-06 19:42 UTC, k-jeonghee commented on 03.programmers-Lv2/003-기능개발.ts
> +}
조건에 맞는 값으로만 반복문을 돌면서 불필요한 분기를 제거했습니다. 그리고 Index 없이 값을 바로 사용할 수 있습니다.

2024-01-07 03:48 UTC, f-lab-jake requested changes

2024-01-07 03:48 UTC, f-lab-jake commented on 02.programmers-Lv1/003-달리기경주.ts
> +        replacePlayer(backRank, frontRank);
`replacePlayer`를 2번 부르는 방식으로 해봅시다.

2024-01-07 03:48 UTC, f-lab-jake commented on 02.programmers-Lv1/003-달리기경주.ts
> +        rankedList[frontPlayer] = frontRank + 1;
`backRank + 1 = frontRank`가 성립할때만 가능한 코드입니다.

2024-01-07 03:48 UTC, f-lab-jake commented on 02.programmers-Lv1/004-추억점수.ts
> +    );
`photo`에 각 요소가 `group`인 셈인가요? 의미를 파악하기 어렵습니다.
그냥 `photos` `photo` 하던가, 아니면 저런건 그냥 `x` `i` 같은거 해도 괜찮습니다.

2024-01-07 03:48 UTC, f-lab-jake commented on 02.programmers-Lv1/006-같은숫자는싫어.ts
> +        if (v !== arr[i - 1]) answer.push(v);
요렇게하면 `arr[-1]`을 액세스하게 되죠?

2024-01-07 03:48 UTC, f-lab-jake commented on 03.programmers-Lv2/005-프로세스.ts
> +    const [...queue] = priorities.entries();
`const queue = [...priorities.entries()];`
나
`const queue = Array.from(priorities.entries());`
의 방법이 있습니다.

2024-01-07 03:48 UTC, f-lab-jake commented on 03.programmers-Lv2/003-기능개발.ts
> +    let target = requiredDays.splice(0, 1)[0];
`.splice(0, 1)`는 왜한거지요?

2024-01-07 06:37 UTC, k-jeonghee commented on 02.programmers-Lv1/006-같은숫자는싫어.ts
> +        if (v !== arr[i - 1]) answer.push(v);
넵! 방어로직을 추가했습니다.

2024-01-07 06:38 UTC, k-jeonghee commented on 03.programmers-Lv2/003-기능개발.ts
> +    let target = requiredDays.splice(0, 1)[0];
초기값 설정과 관련이 있어서 함께 수정하고 제거했습니다.

2024-01-07 06:39 UTC, k-jeonghee commented on 02.programmers-Lv1/003-달리기경주.ts
> +        replacePlayer(backRank, frontRank);
매개변수의 순서를 바꿔 전달하는 방법으로 분기해보았어요

2024-01-07 11:58 UTC, f-lab-jake requested changes

2024-01-07 11:58 UTC, f-lab-jake commented on 02.programmers-Lv1/006-같은숫자는싫어.ts
> +        if (v !== arr[i - 1] ?? v) answer.push(v);
이건 의미가 없죠. `arr[-1]`이 실제로 의미해하는게 `v`가 되나요?
애초에 `arr[-1]`을 읽는걸 피해야합니다.

2024-01-11 05:14 UTC, f-lab-jake approved these changes

2024-01-11 07:16 UTC, merged