[24.01.09] 알고리즘 문제 풀이
k-jeonghee/algorithm pull request #8
Opened 2024-01-09 14:29 UTC by k-jeonghee

@f-lab-jake 
멘토님, 새로운 문제 풀이와 큐 구현 PR 올립니다.
`[006-다리를지나는트럭.ts]`은 잠시 넘겨주세요. 해당 문제는 조금만 더 고민해보고 다시 올리겠습니다.

2024-01-11 05:14 UTC, f-lab-jake commented
다리를지나는트럭 다 푼건가요?

2024-01-14 04:47 UTC, f-lab-jake requested changes

2024-01-14 04:47 UTC, f-lab-jake commented on 03.programmers-Lv2/006-다리를지나는트럭.ts
> +            weight >= sum + truck_weights[0] &&
지금 `truck_weights[0]`이 undefined일 경우가 있찌 않나요? `truck_weights.length` 조건이 없으니까요.

2024-01-14 13:02 UTC, k-jeonghee commented on 03.programmers-Lv2/006-다리를지나는트럭.ts
> +            weight >= sum + truck_weights[0] &&
`truck_weights.length > 0`라는 조건을 주어도 `trucks.length`로 통과되면 `truck_weights[0]`은 undefined입니다. if문 분기 조건에도 추가를 해주는 것이 좋을까요?

2024-01-14 14:09 UTC, f-lab-jake requested changes

2024-01-14 14:09 UTC, f-lab-jake commented on 03.programmers-Lv2/006-다리를지나는트럭.ts
> +            weight >= sum + truck_weights[0] &&
일단 그렇게 하는게 맞는 코드입니다. 그런데 좀더 좋은 방법이 있을거 같네요.

2024-01-14 14:10 UTC, f-lab-jake requested changes

2024-01-14 14:10 UTC, f-lab-jake commented on 03.programmers-Lv2/006-다리를지나는트럭.ts
> +            const [passedTruckWeight, passedSec] = trucks.shift()!;
마찬가지로 요부분도 위험합니다. `trucks[0]`에 값이 있는게 왜 보장이 되는지 코드가 설명하지 못합니다.

2024-01-15 13:31 UTC, k-jeonghee commented on 03.programmers-Lv2/006-다리를지나는트럭.ts
> +            frontTruck &&
`trucks_weights[0]`을 확인하는 분기를 추가했습니다. 이 분기를 한번 통과한 뒤로는 `trucks[0]`값이 마지막으로 제거되면 while문을 벗어나게 되어 undefined를 피할 수 있는데 이 방법은 어떨까요?

2024-05-18 03:04 UTC, merged